name: cherrydice # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A fantastic Dice Roller! # 79 char long summary
description: |
  Cherry Dice - dice roller helps you and your rpg group roll easily any dice you want. You can even copy the text for proof at rpg calls. Play D&D, Shadowrun, Tormenta, Morpho and other RPG platforms with Cherry Dice by your side for easy rolls.

  After a roll, you can easily share the result with all your friends!


  ROLL DICE FAVORITES
  Dice inputs can be saved as "favorites" and rolled with a single tap. Favorites can have any name and can be grouped by category - useful for when you are playing several characters or want to keep things organized.

  DICE ROLL HISTORY
  A list of previous dice roll results is also provided, with the most recent result at the top of the list. Tapping an item in the list will cause it to be rolled again. Previous dice rolls can be shared individually.

  NOTEPAD
  Notes are very important! with Cherry Dice you can save them even separated by categories.



  DM TOOLS
  We want to add maximum ease for you, and with that in mind we will be developing several solutions for DM.

  RIDDLE GENERATOR
  Generate riddles easily, then share them even easier.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  electron-app:
    source: app/
    plugin: nodejs

    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    
    after:
      - desktop-gtk2

    build: node_modules/.bin/electron-builder
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules
  
apps:
  cherrydice:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/app/cherrydice
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
